config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get    '/signup',  to: 'users#new'
  resources :users, except: :new

  resources :jobs

  resources :likes, only: [:create, :update, :destroy]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :employee
  belongs_to :job

  validates :employee_id, uniqueness: { scope: :job_id }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :logged_in_user
  before_action :set_job, only: [:create, :update, :destroy]
  # before_action :set_employee, only: [:create, :update, :destroy]

  def create
    case current_user.type
    when "Employer"
      # FIXME:
      # @like = Like.create!(employee: @employee, job: @job, job_like: params[:like])
    when "Employee"
      @like = Like.create!(employee: current_user, job: @job, employee_like: params[:like])
    end
  end

  def update
    @like = Like.find_by(employee: current_user, job: @job)
    case current_user.type
    when "Employer"
      # FIXME:
      # @like.update!(job_like: params[:like])
    when "Employee"
      @like.update!(employee_like: params[:like])
    end
  end

  def destroy
    Like.find_by(employee: current_user, job: @job).destroy!
  end

  private

    def set_job
      @job = Job.find_by(id: params[:job_id])
    end

    # def set_employee
    #   @employee = Employee.find_by(id: params[:employee_id])
    # end
end

app/views/likes/_like.html.erb
<span id="job_<%= job.id %>">
  <% if like %>
    <% if like.employee_like && like.job_like %>
      <%= link_to "マッチ", like_path(id: like.id, job_id: job.id, like: false), method: :patch, remote: true %>
    <% elsif like.employee_like %>
      <%= link_to "いいね済み", like_path(id: like.id, job_id: job.id), method: :delete, remote: true %>
    <% else %>
      <%= link_to "いいね", like_path(id: like.id, job_id: job.id, like: true), method: :patch, remote: true %>
    <% end %>
  <% else %>
    <%= link_to "いいね", likes_path(job_id: job.id, like: true), method: :post, remote: true %>
  <% end %>
</span>

app/views/likes/create.js.erb
document.getElementById('job_<%= @job.id %>').outerHTML = "<%= escape_javascript(render 'like', like: @like, job: @job) %>";

app/views/likes/destroy.js.erb
document.getElementById('job_<%= @job.id %>').outerHTML = "<%= escape_javascript(render 'like', like: @like, job: @job) %>";

app/views/likes/update.js.erb
document.getElementById('job_<%= @job.id %>').outerHTML = "<%= escape_javascript(render 'like', like: @like, job: @job) %>";